name: CI

on:
 pull_request:
  branches: [main]

 jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: instalar dependencias
      run: npm install
    - name: rodar os testes
      run: npm test